name: 'Build Power BI Connector'
description: 'Compiles the Power BI connector and uploads it as an artifact'
inputs:
  sdk-path:
    description: 'Path to the PowerQuery SDK directory'
    required: true
  working-directory:
    description: 'Working directory where the connector project is located'
    required: false
    default: '.'
  artifact-name:
    description: 'Name for the uploaded artifact'
    required: false
    default: 'firebolt-connector'
outputs:
  connector-path:
    description: 'Path to the compiled connector file'
    value: ${{ steps.compile.outputs.connector-path }}
  artifact-name:
    description: 'Name of the uploaded artifact'
    value: ${{ inputs.artifact-name }}
runs:
  using: 'composite'
  steps:
    - name: Compile Power BI Connector
      id: compile
      shell: powershell
      working-directory: ${{ inputs.working-directory }}
      run: |
        Write-Host "Compiling Power BI Connector..."
        # Find MakePQX.exe in the SDK tools directory
        $toolsDir = Join-Path "${{ inputs.sdk-path }}" "tools"
        $makePQXPath = Join-Path $toolsDir "MakePQX.exe"

        Write-Host "Found MakePQX.exe at: $makePQXPath"

        # Define paths
        $projectPath = "$PWD"
        $mezPath = "$PWD\Firebolt.mez"

        # Compile the extension using MakePQX
        Write-Host "Compiling Power BI connector using MakePQX.exe..."
        & "$makePQXPath" compile

        Write-Host "Power BI Connector compiled successfully"

        # Copy the compiled mez file to the current directory
        Copy-Item -Path "$PWD\bin\AnyCPU\Debug\power-bi-firebolt.mez" -Destination "$PWD\Firebolt.mez" -Force -ErrorAction Stop

        # Set output for the next step
        echo "connector-path=$PWD\Firebolt.mez" >> $env:GITHUB_OUTPUT

    - name: Upload Connector Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.working-directory }}/Firebolt.mez
        retention-days: 30
